# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               EMBC
tagline:             EMBC Consulting
url:                 http://bigdatalib.github.io/poole/
paginate:            1
baseurl:             http://bigdatalib.github.io/poole/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              NS
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
